import 'package:words_without_meaning/lists/GrammarLists.dart';
import 'package:words_without_meaning/lists/adjectives_list.dart';

class Nouns extends GrammarLists {
  //all are singular
  static var nouns = [
    "______",
    "abstraction",
    "aeroplane",
    "trope",
    "aesthetic",
    "encroachments",
    "blue-footed booby",
    "matriarch",
    "pragmatist",
    "artisan",
    "archivist",
    "bon vivant",
    "crusader",
    "romantic",
    "superstar",
    "dramatist",
    "wizard",
    "trickster",
    "knight",
    "mystic",
    "lawmaker",
    "diplomat",
    "politician",
    "critic",
    "professor",
    "guardian",
    "visionary",
    "leader",
    "collaborator",
    "black magic",
    "occult",
    "God of toiletry and sanitation",
    "voodoo",
    "abracadabra",
    "bewitchment",
    "charisma",
    "conjuring",
    "sphinx",
    "divination",
    "enchantment",
    "hocus-pocus",
    "hoodoo",
    "incantation",
    "jinx",
    "magnetism",
    "necromancy",
    "occultism",
    "sorcery",
    "thaumaturgy",
    "voodooism",
    "witchery",
    "witching",
    "wizardry",
    "celestial egg",
    "life force",
    "black art",
    "mumbo jumbo",
    "fable",
    "legend",
    "myth",
    "mythology",
    "cow",
    "superstition",
    "tradition",
    "wisdom",
    "ballad",
    "folk story",
    "mythos",
    "oral literature",
    "air",
    "ancient method",
    "consent",
    "ancient way",
    "Spring",
    "angelus",
    "vernacular",
    "angst",
    "animation",
    "infamy",
    "validity",
    "regimentation",
    "antennae",
    "receiver",
    "wire",
    "electricity",
    "horse shit",
    "manure",
    "mail",
    "aerial",
    "reflector",
    "element",
    "transmission line",
    "Gestapo",
    "dipole",
    "communication",
    "autumn",
    "interference",
    "answer",
    "antellope",
    "archetype",
    "ardor",
    "arrow",
    "Atlantic",
    "backbone",
    "barb",
    "Bath",
    "beard",
    "beast",
    "bed",
    "bell",
    "disc drive",

    "bell-rope",
    "bewilderment",
    "bird",
    "bleach",
    "blind man",
    "blood",
    "bluff",
    "boat",
    "body of water",
    "body",
    "book",
    "boulder",
    "box",
    "boxcar",
    "brain",
    "brain-twister",
    "bramble",
    "breast",
    "Breath",
    "brier",
    "bristle",
    "broom",
    "campanile",
    "cannon",
    "canyon",
    "car",
    "illusion",
    "carriage",
    "cathedral",
    "cave",
    "charade",
    "chest",
    "chill",
    "choice",
    "choir",
    "chute",
    "cigarette",
    "circle",
    "circus",
    "city",
    "clapboard",
    "cleft",
    "closed book",
    "cloud",
    "coat",
    "coffin",
    "cognate",
    "color",
    "commonwealth",
    "company",
    "compensation",
    "complexity",
    "complication",
    "component",
    "confusion",
    "console",
    "constituent",
    "traffic",
    "conundrum",
    "corp",
    "tobacco",
    "costume",
    "country",
    "county",
    "crag",
    "crate",
    "crown",
    "crucifix",
    "cryptogram",
    "crystal",
    "dart",
    "data plan",
    "data",
    "dawn",
    "day",
    "death",
    "debris",
    "deck of cards",
    "decorum",
    "threshold",
    "design",
    "seed",
    "despair",
    "detail",
    "diety",
    "dilemma",
    "disapproval",
    "disguise",
    "Dispatch",
    "distraction",
    "dog",
    "door",
    "doubt",
    "dream",
    "LSD",
    "dregs",
    "dross",
    "dynasty",
    "ear",
    "earth",
    "echo",
    "embarrassment",
    "empire",
    "energy",
    "enigma",
    "entanglement",
    "escape",
    "Everything",
    "exterior",
    "eye",
    "fate",
    "face",
    "fake",
    "false colors",
    "false front",
    "field",
    "fire",
    "flag",
    "flame",
    "flash",
    "fling",
    "fluid",
    "fool",
    "foot",
    "force",
    "form",
    "frame of mind",
    "front",
    "event horizon",
    "horizon",
    "boundary",
    "perspective",
    "pickup truck",
    "Volvo",
    "sports car",
    "prospect",
    "scope",
    "border",
    "compass",
    "ken",
    "limit",
    "purview",
    "range",
    "reach",
    "realm",
    "sphere",
    "stretch",
    "vista",
    "field of vision",
    "frontage",
    "frontier",
    "game",
    "garnish",
    "gauze",
    "gem",
    "genre",
    "ghost",
    "glue",
    "goddess",
    "helicopter",
    "hovercraft",
    "goal",
    "God",
    "grain",
    "gravel",
    "grit",
    "groove",
    "guise",
    "gun",
    "gunpowder",
    "gut",
    "habit",
    "hand",
    "hanged man",
    "healed",
    "health",
    "heap",
    "heart",
    "heaven",
    "heavenly body",
    "hell",
    "hill",
    "hint",
    "hobo",
    "hold",
    "hole",
    "holy text",
    "hope",
    "hot mess",
    "house",
    "humor",
    "idea",
    "idiosyncrasy",
    "idiot",
    "impasse",
    "imposter",
    "Indian",
    "ingredient",
    "elders",
    "Ancient one",
    "grapevine",
    "key insight",
    "insight",
    "instant",
    "interval",
    "intricacy",
    "item",
    "jacket",
    "jazz musician",
    "jazz tune",
    "jewel",
    "jouney",
    "judgement",
    "junk",
    "kingdom",
    "knell",
    "knotty question",
    "labyrinth",
    "lady",
    "lake",
    "land",
    "landlord",
    "language",
    "lawn",
    "feedback loop",
    "life force",
    "life",
    "lift",
    "light",
    "Liquor",
    "list",
    "litter",
    "look",
    "lost art",
    "love",
    "lover",
    "flying fortress",
    "dashboard shrine",
    "lumber",
    "machine",
    "manner",
    "marijuana",
    "marrow",
    "mask",
    "masonry",
    "material",
    "matrix",
    "matter",
    "maze",
    "member",
    "Membrane",
    "memory",
    "cup of tea",
    "metal",
    "method",
    "mettle",
    "mind",
    "mind-boggler",
    "mineral",
    "mirage",
    "mode",
    "monarch",
    "monarchy",
    "mood",
    "morale",
    "morning",
    "mystery",
    "mystification",
    "nation",
    "nerve",
    "nettle",
    "night",
    "number",
    "offal",
    "old custom",
    "old-red",
    "One",
    "ore",
    "outlook",
    "Oval",
    "Pagoda",
    "parachute",
    "part",
    "particle",
    "pass-phrase",
    "password",
    "wolf",
    "electron",
    "atom",
    "wolf-pack",
    "cat",
    "lion",
    "pattern",
    "pebble",
    "peculiarity",
    "people",
    "perplexity",
    "phone",
    "phony",
    "phrase",
    "piece",
    "pile",
    "pipe",
    "pissing stone",
    "pit",
    "plain",
    "plane of existence",
    "planets",
    "playing field",
    "pledge",
    "plight",
    "haiku",
    "limmerick",
    "scrawl",
    "chicken-scratch",
    "poem",
    "poetry",
    "point",
    "pole",
    "poser",
    "possession",
    "power",
    "predicament",
    "pretense",
    "shield",
    "prickle",
    "principality",
    "principle",
    "doorkeeper",
    "problem",
    "cipher",
    "procedure",
    "process",
    "program",
    "prong",
    "prophet",
    "propos",
    "province",
    "psyche",
    "pulse",
    "punch card",
    "put-on",
    "puzzle",
    "puzzlement",
    "quandary",
    "question",
    "quill",
    "radar",
    "radio",
    "railroad",
    "rain",
    "ray",
    "reality",
    "realm",
    "rebus",
    "refuse",
    "reign",
    "resolution",
    "resource",
    "riddle",
    "ridicule",
    "rifle",
    "road",
    "rock",
    "romance",
    "room",
    "root",
    "rubbish",
    "rubble",
    "ruin",
    "rule",
    "rummage",
    "sacred text",
    "sarcasm",
    "saxophone",
    "scarf",
    "scepter",
    "schoolhouse",
    "school",
    "score",
    "scorn",
    "scrap",
    "seaboard",
    "section",
    "code",
    "semblance",
    "shadow",
    "shaft",
    "sheriff",
    "ship",
    "shit",
    "shop",
    "shoulder",
    "show",
    "shower",
    "shrine",
    "side",
    "sixty-four dollar question",
    "skin",
    "sky",
    "smoke",
    "smooth talker",
    "snow",
    "song",
    "soul",
    "sovereignty",
    "spacecraft",
    "sphere",
    "spike",
    "spine",
    "spirit",
    "spool",
    "spur",
    "square",
    "star",
    "State",
    "statement",
    "station",
    "speed",
    "step",
    "stone",
    "work",
    "toil",
    "stonework",
    "store",
    "story",
    "strait",
    "stripe",
    "orbit",
    "perigee",
    "stroke",
    "mofo",
    "stumper",
    "style",
    "subdivision",
    "substance",
    "summer",
    "deposit",
    "euphoria",
    "accumulation",
    "stockpile",
    "stash",
    "hoard",
    "cigar",
    "sun",
    "sweepings",
    "swing",
    "sword",
    "winter",
    "syrum",
    "target environment",
    "target",
    "taxi",
    "technology",
    "equity",
    "teaser",
    "virus",
    "technique",
    "tenor",
    "tent",
    "terrace",
    "territory",
    "thigh",
    "thing",
    "thinking man",
    "thistle",
    "thorn",
    "thought",
    "throat",
    "throne",
    "tone",
    "tongue",
    "tough nut to crack",
    "tough proposition",
    "tower",
    "trace",
    "tract",
    "train",
    "trash",
    "trend",
    "tribunal",
    "twister",
    "unicorn",
    "unit",
    "vacuum tube",
    "vehicle",
    "vein",
    "veneer",
    "verse",
    "view",
    "visionary",
    "being",
    "mystic",
    "swami",
    "voice",
    "walrus",
    "fig leaves",
    "leaf",
    "leaflettes",
    "Void",
    "the Void",
    "boob job",
    "boobs",
    "lagoon",
    "serpent",
    "musket",
    "salmon run",
    "medicine",
    "reproduction",
    "clone",
    "dearth",
    "defect",
    "failing",
    "failure",
    "fault",
    "flaw",
    "frailty",
    "glitch",
    "insufficiency",
    "lack",
    "scarcity",
    "shortage",
    "shortcoming",
    "book of the dead",
    "weakness",
    "copy",
    "Pyramids",
    "edifice",
    "memorial",
    "monolith",
    "shrine",
    "tomb",
    "cairn",
    "cenotaph",
    "mastaba",
    "obelisk",
    "tribute",
    "counterfeit",
    "duplicate",
    "duplication",
    "facsimile",
    "fake",
    "image",
    "likeness",
    "match",
    "reflection",
    "replica",
    "sham",
    "carbon copy",
    "mirroring",
    "paralleling",
    "tree of the knowledge",
    "firmament",
    "war",
    "wasp",
    "waste",
    "way",
    "weapon",
    "spindle",
    "simulation",
    "soil",
    "dirt",
    "dust",
    "web",
    "whale",
    "ways",
    "frost",
    "ice",
    "glass",
    "mud",
    "whither",
    "whore",
    "willpower",
    "encyclicals",
    "wind",
    "window dressing",
    "window",
    "wing",
    "wire",
    "wives tale",
    "Word",
    "word",
    "tool",
    "prophesies",
    "dirt",
    "earth",
    "grime",
    "lint",
    "powder",
    "sand",
    "soil",
    "soot",
    "ashes",
    "cinders",
    "filth",
    "flakes",
    "fragments",
    "granules",
    "grit",
    "ground",
    "loess",
    "refuse",
    "smut",
    "desert",
    "Sahara",
    "tools",
    "world",
    "wound",
    "noise",
    "footprint",
    "signal-to-noise ratio",
    "writing desk",
    "Peninsula",
    "hunk",
    "hulk",
    "substance",
//  "another",
//  "antique",
//  "away",
//  "blue",
//  "break",
//  "ghostly",
//  "hear",
//  "heard",
//  "kept",
//  "old",
//  "pure",
//  "quality",
//  "quivering",
//  "rage",
//  "recall",
//  "reckoning",
//  "red"
//  "sort",
//  "sown",
//  "sparkle",
//  "stare",
//  "static",
//  "stem",
//  "swelling",
//  "tall",
//  "top",
//  "Unseals",
//  "within",
//"kind",
//"type",
  ];

  static var concepts = [
    "fertility",
    "sexuality",
    "a priori",
    "a posteriori",
    "Absolute time and space",
    "Absolute",
    "Abstract and concrete",
    "abstraction",
    "acoustics",
    "Adiaphora",
    "Aesthetic emotions",
    "Aesthetic interpretation",
    "aesthetic",
    "Agathusia and aschimothusia",
    "Alief",
    "All men are created equal",
    "analysis",
    "Analytic-synthetic distinction",
    "anatomy",
    "Anthropic principle",
    "Antinomian",
    "Antinomy",
    "Apeiron",
    "appearance",
    "approach",
    "Arborescent",
    "archaeology",
    "archetype",
    "architecture",
    "armageddon",
    "Art manifesto",
    "Artha",
    "aspect",
    "astronautics",
    "astronomy",
    "Atman",
    "atmosphere",
    "attrocity",
    "Aufheben",
    "Autonomy",
    "Avadhuta",
    "Avant-garde",
    "Avatar",
    "bacteriology",
    "basis",
    "bearing",
    "Beauty",
    "behavior",
    "behavioural",
    "Being",
    "Belief",
    "miscreant",
    "Binary opposition",
    "biochemistry",
    "bioclimatology",
    "bioethics",
    "Biofact",
    "biogeochemistry",
    "biogeography",
    "biology",
    "biotechnology",
    "Body without organs",
    "Boredom",
    "Brahman",
    "Brahmanda",
    "Brain in a vat",
    "broken",
    "Brute fact",
    "calculation",
    "calibration",
    "Cambridge change",
    "Camp",
    "Cartesian Other",
    "Cartesian Self",
    "Categorical imperative",
    "Categorization",
    "Category of being",
    "Causal adequacy principle",
    "Causality",
    "Chaitanya",
    "Chakra",
    "character",
    "characteristic",
    "Charvaka",
    "chemistry",
    "Choice",
    "Civic virtue",
    "civilisation",
    "Class consciousness",
    "Class",
    "Cogito ergo sum",
    "Cognitive closure",
    "colour composition",
    "Commensurability",
    "Common good",
    "Common sense",
    "comparison",
    "complexion",
    "Composition of Causes",
    "Compossibility",
    "Conatus",
    "concept",
    "Concept",
    "Condition of possibility",
    "Conjecture",
    "connection",
    "Conscience",
    "Consent",
    "Construct",
    "Cooperative principle (Gricean maxims)",
    "coordinates",
    "courage",
    "Crazy wisdom",
    "Creativity",
    "crisis",
    "Cultural hegemony",
    "Cultural sensibility",
    "Cuteness",
    "Daimonic",
    "Darshana",
    "data acquisition",
    "data analysis",
    "De dicto and de re",
    "dead reckoning",
    "decision process",
    "Definition",
    "demography",
    "description",
    "Descriptive knowledge",
    "Desiring-production",
    "detection",
    "determination",
    "Dharma",
    "Dhyana",
    "Diksha",
    "Disciplinary institution",
    "Discourse",
    "Disgust",
    "dispersion calculation",
    "disposition",
    "Dispositional and occurrent belief",
    "distance",
    "Distributive justice",
    "Distrust",
    "division",
    "Documentality",
    "Dogma",
    "domain",
    "dominion",
    "dose-effect",
    "druthers",
    "Duty",
    "Dwelling",
    "ecology",
    "ecosystem",
    "Ecotechnics",
    "Ecstasy",
    "Efficient cause",
    "Elegance",
    "Embodied cognition",
    "Emergence",
    "emission",
    "Empirical method",
    "Empirical relationship",
    "Empirical research",
    "emptiness",
    "enterprise",
    "Entertainment",
    "enthusiasm",
    "Entity",
    "Epistemic injustice",
    "Epistemic virtue",
    "Epoché",
    "Eroticism",
    "essence",
    "Essence",
    "eternity",
    "Eternity",
    "Ethics of care",
    "ethics",
    "Eudaimonia",
    "Eupraxis",
    "Excellence",
    "existence",
    "Existence",
    "Existential phenomenology",
    "Experience",
    "experiment",
    "facet",
    "facility",
    "Fact",
    "factor",
    "Fidelity",
    "Final anthropic principle",
    "Final cause",
    "fluid theory",
    "forecast",
    "Formal cause",
    "Formal theorem",
    "Four causes",
    "Free will",
    "Friendship",
    "fundamental",
    "Gemeinschaft and Gesellschaft",
    "genetic engineering",
    "geodesy",
    "geography",
    "geology",
    "geometric correction",
    "geomorphology",
    "geotechnology",
    "Gettier problem",
    "glaciology",
    "global megatrend",
    "global model",
    "Glory",
    "granulometry",
    "gridding",
    "guideline",
    "haematology",
    "half-life",
    "Half-truth",
    "Happiness",
    "Harmony",
    "speech",
    "Health",
    "Here is a hand",
    "Heteronomy",
    "historical research",
    "History and Class Consciousness",
    "history",
    "Human rights",
    "hydraulics",
    "I know that I know nothing",
    "Idea",
    "Ideal (ethics)",
    "Ideal speech situation",
    "Identity",
    "Ideological repression",
    "Ideology",
    "Ignoramus et ignorabimus",
    "Ignorance",
    "Immanence",
    "Immanent critique",
    "Implicate and explicate order according to David Bohm",
    "indicator",
    "Infallibility",
    "Inference",
    "Infinity",
    "Information",
    "Injustice",
    "Innocence",
    "innovation",
    "Instantiation principle",
    "Institutional cruelty",
    "Integral philosophy",
    "Integral yoga",
    "Intellectual responsibility",
    "Intention",
    "Interpellation",
    "interpolation",
    "Intrinsic and extrinsic properties",
    "Intuition",
    "inventory",
    "invisibility",
    "Involution",
    "Ius indigenatus",
    "Judgement",
    "jurisprudence",
    "Jus sanguinis",
    "Jus soli",
    "Just War",
    "Justice",
    "Kala",
    "Kalachakra",
    "Karma yoga",
    "Karma",
    "Kathekon",
    "Kaula",
    "KK thesis",
    "Knowledge",
    "Kundalini energy",
    "Last man",
    "law",
    "Laïcité",
    "League of peace",
    "Life imitating art",
    "limitation",
    "Logic",
    "Logical consequence",
    "Logical constant",
    "Logical form",
    "Logical truth",
    "Logos",
    "Love",
    "Loyalty",
    "Magnificence",
    "Mansion of Many Apartments",
    "Mantra",
    "mapping",
    "Marx’s theory of alienation",
    "Marx’s theory of human nature",
    "Master-slave dialectic",
    "Material cause",
    "Matter",
    "Max Scheler’s Concept of Ressentiment",
    "Maya",
    "Meaning of life",
    "Meaning",
    "measurement",
    "Mental representation",
    "Mercy",
    "method",
    "methodology",
    "Mimesis",
    "Mind",
    "mineralogy",
    "Minority",
    "model",
    "Moksha",
    "Molyneux’s Problem",
    "Moral responsibility",
    "mortality",
    "Motion",
    "motivation",
    "Mundane reason",
    "Name",
    "Nation",
    "Natural and legal rights",
    "Nature",
    "Necessary and sufficient condition",
    "Negative capability",
    "Nonmaleficence",
    "Norm of reciprocity",
    "Norm",
    "Normative science",
    "Notion",
    "Object",
    "Objectivity",
    "observation",
    "oceanography",
    "Om",
    "Omphalos hypothesis",
    "oncology",
    "Ontology",
    "Panopticon",
    "Paradox",
    "parameter",
    "Passions",
    "pathology",
    "Pattern",
    "Peace",
    "Percept",
    "Perception",
    "Peripatetic axiom",
    "Perpetual peace",
    "Philosophical analysis",
    "Philosophy of futility",
    "Physical body",
    "physics",
    "trope",
    "physiology",
    "Physis",
    "pilot project",
    "Pneuma",
    "Political consciousness",
    "pollution",
    "Polychotomous key",
    "population statistics",
    "Possible world",
    "Posthegemony",
    "Prakriti",
    "Pratyabhijna",
    "Presupposition",
    "Primum non nocere",
    "Principle of double effect",
    "Principle",
    "prison",
    "prisoner",
    "Problem of induction",
    "Problem of other minds",
    "processing technique",
    "Prohairesis",
    "Property",
    "Propositional attitude",
    "protection",
    "prototype",
    "psychology",
    "Purusha",
    "Qualia",
    "quality control",
    "quality",
    "Quality",
    "Quantity",
    "Raja yoga",
    "Rajas",
    "random test",
    "Rasa",
    "Rationality",
    "Real freedom",
    "Reason",
    "Reciprocity",
    "Reference",
    "Reform",
    "Regress argument",
    "relationship",
    "Ren",
    "research of the effects",
    "research project",
    "research",
    "residue analysis",
    "Right to exist",
    "Righteousness",
    "Rights",
    "Ring of Gyges",
    "risk analysis",
    "risk-benefit analysis",
    "Rule of Rescue",
    "rural architecture",
    "safety analysis",
    "safety study",
    "Sahaja",
    "Samarasa",
    "sampling technique",
    "sampling",
    "Satchidananda",
    "Satori",
    "Sattva",
    "science",
    "Sea of Beauty",
    "selection",
    "Self",
    "self-monitoring",
    "Self-realization",
    "Semantics",
    "Sense data",
    "sensitivity",
    "Set",
    "Shabda",
    "Shakti",
    "silence",
    "Simulacrum",
    "Simulated reality",
    "Simulation hypothesis",
    "simulation",
    "Sittlichkeit",
    "Slippery slope",
    "Social contract",
    "Society",
    "Soku hi",
    "Sortal",
    "space research",
    "spatial distribution",
    "spectroscopy",
    "Speculative reason",
    "speed",
    "State of nature",
    "statistical analysis",
    "statistical data",
    "statistical series",
    "statistics",
    "stream measurement",
    "structure-activity relationship",
    "study",
    "Style",
    "Subject",
    "Sublime",
    "chickenshits",
    "Substance theory",
    "Substantial form",
    "Substitution",
    "Suffering",
    "Sunyata",
    "Supermind",
    "Superrationality",
    "superstition",
    "survey",
    "suzerainty",
    "Symbol",
    "synecology",
    "synergism",
    "Syntax",
    "systems analysis",
    "systems comparison",
    "systems theory",
    "Tamas",
    "Tantra",
    "Taste",
    "technique",
    "technology",
    "tectonics",
    "telemetry",
    "Telos",
    "temperament",
    "terminology",
    "test animal",
    "test organism",
    "test",
    "The Golden Rule",
    "The saying and the said",
    "Theorem",
    "Theory of justification",
    "thermodynamics",
    "thesis",
    "Thought",
    "threshold ",
    "Thrownness",
    "Thumos",
    "Ti",
    "time",
    "Time",
    "tracer technique",
    "traffic",
    "Trailokya (Triloka)",
    "trait",
    "Transcendent",
    "Transcendental apperception",
    "Transworld identity",
    "trend",
    "Trika",
    "Trilok (Jainism)",
    "Triratna",
    "Trust",
    "Truth value",
    "truth",
    "Truth",
    "type",
    "Unity of science",
    "Unity of the proposition",
    "Universal",
    "Universality",
    "Unobservable",
    "urban study",
    "Utility",
    "Vajrayana",
    "Validity",
    "value",
    "Value",
    "Vamachara",
    "Virtual",
    "Virtue",
    "visibility",
    "vital spark",
    "vitality",
    "volcanology",
    "warmth",
    "waste statistics",
    "weather forecasting",
    "Well-founded phenomenon",
    "Work of art",
    "Wrong",
    "Yi",
    "Yidam",
    "Yoga",
    "Zeitgeist",
    "zoology",
    "Übermensch",
  ];

  static var strangeGroupsOfPeople = [
    "travelling",
    "dufus",
    "",
    Adjectives.adjectives[
            GrammarLists.getRandFromRange(Adjectives.adjectives.length)] +
        " " +
        "horse breeding",
    "dog breeders",
    concepts[
    GrammarLists.getRandFromRange(concepts.length)],
    "foam rubber afficionados",
    "hot baby",
    "candycane",
    "Playa",
    "horse riding",
    Adjectives.adjectives[
            GrammarLists.getRandFromRange(Adjectives.adjectives.length)] +
        " " +
        nouns[GrammarLists.getRandFromRange(nouns.length)],
  ];

  static var travels = [
    "expedition",
    "footslog",
    "hegira",
    "hike",
    "long haul",
    "march",
    "odyssey",
    "peregrination",
    "slog",
    "tramp",
    "travel",
    "trip",
    "peon",
    "child",
    "side effect",
    "adult",
    "boat trip",
    "boating",
    "bout",
    "campaign",
    "caravan",
    "cavalcade",
    "circle tour",
    "circuit",
    "company",
    "course",
    "crew",
    "crossing",
    "crowd",
    "cruise",
    "crusade",
    "enterprise",
    "entrada",
    "errand",
    "excursion",
    "expedition",
    "exploration",
    "explorers",
    "fleet",
    "foray",
    "getaway",
    "hitch",
    "hop",
    "jaunt",
    "journey",
    "junket",
    "mission",
    "outing",
    "overnight",
    "party",
    "passage",
    "patrol",
    "peregrination",
    "picnic",
    "posse",
    "progress",
    "quest",
    "ramble",
    "road",
    "round",
    "round trip",
    "roundabout",
    "run",
    "safari",
    "sail",
    "sailing",
    "sea trip",
    "shift",
    "spell",
    "squadron",
    "stretch",
    "stump",
    "swing",
    "tour",
    "travel",
    "travellers",
    "travels",
    "trek",
    "trick",
    "trip",
    "turn",
    "undertaking",
    "voyage",
    "voyagers",
    "whistle-stop",
  ];

  static var abstractActivities = [
    "contract",
    "voyage",
    "expedition",
    "odyssey",
    "campaign",
    "crossing",
    "enterprise",
    "excursion",
    "expedition",
    "exploration",
    "foray",
    "jaunt",
    "journey,",
    "mission",
    "travels",
    "undertaking",
    "voyage",
  ];

  static var landsAndEmpires = [
    "oases west of Egypt",
    "Libyan Desert",
    "Austrian Empire",
    "American southwest",
    "East Indies",
    "East Texas",
    "Outback",
    "Down under",
    "Mountains",
    "French Alps",
    "Italian Alps",
    "German Alps",
    "distant lands",
    "badlands",
    "big city",
    "south side of Chicago",
    "mines of hell",
    "outer rim",
    "abandoned lands",
    "Turkey",
    "Kurdistan highlands",
    "Russian steppe",
  ];

  static var personalityTypes =
  [
    "matriarch",
    "pragmatist",
    "artisan",
    "archivist",
    "bon vivant",
    "crusader",
    "romantic",
    "superstar",
    "dramatist",
    "wizard",
    "trickster",
    "knight",
    "mystic",
    "lawmaker",
    "diplomat",
    "politician",
    "critic",
    "professor",
    "guardian",
    "visionary",
    "leader",
    "collaborator",
  ];

  static var groupsOfAnimalsOrPeople = [
    "wolves",
    "college fraternity",
    "coworkers who care little",
    "bad parents",
    "wild animals",
    "an idiot tribe",
    "a pod of benevolent whales",
    "really smart animals",
    "psychopath parents",
    "Eastern Orthodox priests",
    "a mystic",
    "a used car salesman",
    "a magician",
    "silly clowns",
    "an astronaut named Willy",
    "somebody named Willy",
    "parents with the rhyming names Sal and Val",
    "a small electronic computer",
    "Kurdish rebels",
  ];

  static var randomIncorporation = [
    "Incorporated!!!",
    ", LLC",
    "Corp",
    "®",
    "GmbH & Co. KG",
    "& Co.",
    "GmbH",
    "AG",
    "-Zeiss-Stiftung",
    "-Flugdienst",
    "-Spiegel",
    "Bahn",
    "Bank",
    "Grammophon",
    "Messe",
    "Pfandbriefbank",
    "Post",
    "Telekom",
    "Vermögensberatung",
    "Partners",
    "Holdings LLC",
    "Petrolub",
    "Group",
    "National Corporation",
    "+ Jahr",
    "& Koch",
    "Druckmaschinen",
    "a division of Redmond Coil, LLC",
    "Deutsche Werft, GmbH",
    "-Aéropostale",
    "run by Millenials",
    "dream sequence",
    "fuckin’ Today’s Heroes",
    "dorks",
    "jazz idiots",
    "stoned & depraved LLC",
    "Smokers UNL.",
    "bROgrammers United",
    "if you’re this far you’re in too deep",
    "National Correspondance Films of America",
    "Satan",
    "the good people of Switzerland",
    "Virgins for More Sex!",
    "some dumbass",
    "Boeing, my favorite airplane builder",
    "musings of a 737 pilot",
    "punctuation UNLIMITED because we just don’t care.",
    "nobody. because Trump took all the money to build a wall.",
    "the Lesser Gods of Christianity, LLC",
    "the Greater Good Foundation",
    "BS peeps",
    "Sex Hounds, the quiet corp",
  ];

  static var maladies = [
    "cramps",
    "jaundice",
    "DTs",
    "syndrome",
    "mental condition of #stateOfExistence",
    "puking spells",
    "flu",
    "fever",
    "ailment",
    "sickness",
    "infection",
    "",
    athletics[GrammarLists.getRandFromRange(athletics.length)],
    "virus",
    "bacterial infection",
    "(ask your doctor)",
    "Java SDK sickness sweeping the nation",
    "JavaBeans™ blues",
    "IBM secret sauce®",
    "poisoning",

  ];

  static var athletics = [
    "Athletics",
    "Badminton",
    "Baseball",
    "Basketball",
    "BMX racing",
    "Boxing",
    "Canoe/kayak",
    "Cricket",
    "Croquet",
    "Equestrian",
    "Fencing",
    "Field hockey",
    "Football",
    "Golf",
    "Greco-Roman",
    "Handball",
    "Ice hockey",
    "Jeu de",
    "Judo",
    "Karate",
    "Lacrosse",
    "Marathon swimming",
    "Modern pentathlon",
    "Mountain biking",
    "Polo",
    "Rackets",
    "Racquets",
    "Rhythmic Gymnastics",
    "Road cycling",
    "Roque",
    "Rowing",
    "Rugby",
    "Rugby sevens",
    "Sailing",
    "Shooting",
    "Skateboarding",
    "Softball",
    "Sport climbing",
    "Sport",
    "Surfing",
    "Swimming",
    "Synchronized swimming",
    "Table tennis",
    "Taekwondo",
    "Tennis",
    "Track cycling",
    "Trampoline Gymnastics",
    "Triathlon",
    "Tug of",
    "Volleyball",
    "Water motorsports",
    "Water polo",
    "Weightlifting",
  ];
}
