class Verbs
{
  static var verbs = [
    "abandon",
    "accept",
    "ate",
    "bankrupt",
    "beat",
    "beaten",
    "became",
    "mass-produced",
    "captivate",
    "exercised",
    "become something, a... ",
    "load",
    "become",
    "been",
    "began",
    "begin",
    "begun",
    "bend",
    "bent",
    "bet",
    "bid",
    "bit",
    "bite",
    "blew",
    "blow",
    "break",
    "bring",
    "broke",
    "broken",
    "build",
    "burn out",
    "burn",
    "burned",
    "burnt",
    "buy",
    "calm",
    "came",
    "catch",
    "caught",
    "choose",
    "chose",
    "chosen",
    "come",
    "conk out",
    "crawl",
    "cut",
    "debilitate",
    "dig",
    "disable",
    "discharge",
    "disgorge",
    "dive",
    "dived",
    "do in",
    "do",
    "dove",
    "drain",
    "drank",
    "draw",
    "drawn",
    "dream",
    "dreamed",
    "dreamt",
    "drew",
    "dribble",
    "drink",
    "drip",
    "drive",
    "driven",
    "drove",
    "drown",
    "drunk",
    "dug",
    "eat",
    "emptied",
    "entered",
    "evoke",
    "fall",
    "faltered",
    "feel",
    "fell",
    "felt",
    "fight",
    "find",
    "flew",
    "flow",
    "flown",
    "fly",
    "forgave",
    "forget",
    "forgive",
    "forgiven",
    "forgot",
    "forgotten",
    "fought",
    "found",
    "frazzle",
    "freeze",
    "froze",
    "froze",
    "gathers",
    "gave",
    "get lost",
    "get",
    "give",
    "go",
    "got",
    "gotten",
    "grew",
    "grow",
    "grown",
    "had",
    "hang",
    "have",
    "hear",
    "heard",
    "held",
    "hid",
    "hide",
    "hit",
    "hold",
    "hung",
    "hurt",
    "impoverish",
    "jump",
    "keep",
    "kept",
    "killed",
    "knew",
    "know",
    "laid",
    "lain",
    "lay",
    "lead",
    "leave",
    "led",
    "left",
    "lend",
    "lent",
    "let",
    "lie",
    "lose",
    "lost",
    "made",
    "make",
    "meant",
    "meet",
    "met",
    "overdo",
    "overexert",
    "overextend",
    "overfatigue",
    "overfill",
    "overflow",
    "overrun",
    "overtire",
    "overturn",
    "overwork",
    "paid",
    "pay",
    "peter out",
    "poop out",
    "poop",
    "pour",
    "propose",
    "possessed",
    "prostrate",
    "scored",
    "slain",
    "put",
    "ran",
    "rang",
    "read",
    "ride",
    "ring",
    "rise",
    "risen",
    "rode",
    "rose",
    "run out",
    "run over",
    "run ragged",
    "run",
    "rung",
    "said",
    "sang",
    "sap",
    "sat",
    "saw",
    "say",
    "scatter",
    "see",
    "seen",
    "sell",
    "send",
    "sent",
    "shed",
    "show",
    "showed",
    "shown",
    "shut",
    "sing",
    "agitate",
    "sit",
    "sleep",
    "slept",
    "sold",
    "speak",
    "spend",
    "spent",
    "spill over",
    "spill",
    "splash",
    "splatter",
    "spoke",
    "spray",
    "sprinkle",
    "spurt",
    "squirt",
    "stand",
    "steal",
    "stole",
    "stood",
    "stream",
    "suck dry",
    "sung",
    "swam",
    "swim",
    "swum",
    "take",
    "taught",
    "teach",
    "tear",
    "tell",
    "think",
    "thought",
    "threw",
    "throw off",
    "throw",
    "told",
    "took",
    "tore",
    "torn",
    "tucker",
    "understand",
    "understood",
    "upset",
    "use up",
    "wake",
    "walk",
    "wander",
    "weaken",
    "wear down",
    "harass",
    "amuse",
    "wear",
    "went",
    "win",
    "woke",
    "woken",
    "won",
    "wore",
    "worn",
    "wreck",
    "write",
    "wrote",
  ];

  static var verbsPastTense = [
    "abandoned",
    "accepted",
    "ate",
    "beat",
    "loaded",
    "bit",
    "shone",
    "blew",
    "pressed",
    "broke",
    "prevented",
    "burned",
    "smoked",
    "bought",
    "crawled",
    "cut",
    "dug",
    "dove",
    "went",
    "drank",
    "dreamt",
    "agitated",
    "dribbled",
    "drove",
    "flew",
    "fought",
    "got",
    "grew",
    "held",
    "jumped",
    "let",
    "made",
    "paid",
    "poured",
    "put",
    "ran",
    "read",
    "rode",
    "sang",
    "sat",
    "retired",
    "saw",
    "demised",
    "decamped",
    "disavowed",
    "scattereded",
    "spoke",
    "surrender",
    "swam",
    "thought",
    "understood",
    "walked",
    "wandered",
    "went",
  ];


  static var verbsOfFinality = [
    "abandoned all hope",
    "accepted fate",
    "ate poison",
    "bankrupted everyone",
    "beat my own brains to pulp",
    "captivated no one",
    "become nothing",
    "loaded a gun",
    "bit down on the leather",
    "blew up",
    "pressed the red button",
    "broke all the windows",
    "burned out, faded away",
    "smoked a cigarette",
    "bought a sports car and drove it off a cliff",
    "calmed myself",
    "cought the flu",
    "crawled under a rock",
    "cut myself",
    "dug my grave",
    "dove into a dark pool",
    "went down the drain",
    "drank myself into oblivion",
    "dreamed a pleasant dream",
    "dreamt of something else",
    "drew myself a bath",
    "dribbled out this poem",
    "drove into town",
    "drowned myself in alcohol",
    "emptied a clip into the television",
    "felt sick",
    "found I was right all along",
    "flew into the sky",
    "forgave my enemies",
    "forgot what i was saying",
    "forgot everything",
    "fought my friends",
    "found a twenty dollar bill on the ground",
    "froze to death",
    "gave all my money to a bum on the street",
    "got lost",
    "got a disease",
    "grew out of this funk",
    "had everything I'd lost given back to me",
    "hanged myself",
    "heard strange music in my mind",
    "held on for dear life",
    "hid inside for a month",
    "hurt everyone I loved",
    "impoverish myself",
    "jumped off a bridge",
    "kept trying to make sense of this",
    "killed myself",
    "lay down and slept",
    "left",
    "let everyone step on me",
    "lost everything at the poker table",
    "made a fortune",
    "met my maker",
    "paid my staff and walked away",
    "poured another drink",
    "proposed to a perfectly good stranger",
    "lay prostrate",
    "put myself out of my misery",
    "ran away",
    "rang up a friend",
    "read the scriptures",
    "rode a motorcycle",
    "rose from bed",
    "departed this world",
    "said nothing for seven days",
    "sang old songs from my youth",
    "sat down",
    "saw god",
    "scattered like leaves in the wind",
    "sent everyone away",
    "showed this to my friends",
    "shut the back door",
    "slept",
    "sold all my belongings",
    "spent the night in jail",
    "spilled my drink",
    "splattered myself with blood",
    "spoke wise words into the abyss",
    "stood up and declared myself invisible",
    "swam across the lake",
    "taught the deaf to hear and the blind to see",
    "thought, surely I've gone mad",
    "threw a fit",
    "told my friends these words",
    "understood precisely what this meant",
    "upset this delicate balance",
    "used up all my money",
    "walked along the train tracks",
    "wandered alone for many days",
    "went on a journey alone",
    "woke from this strange dream",
    "wrecked my Porsche",
    "wrote these words",
  ];

  static var pastTenseVerbStateOfExistence = [
    "deflated",
    "spent",
    "invigorated",
    "sublime",
    "mystified",
    "stoned",
    "marooned",
    "hopelessly mired in #noun cliché",
    "enriched",
    "hunched over",
    "hung over",
    "obliterated",
    "wasted",
    "surrendered",
    "confused",
    "mentally blown",
    "reborn",
    "dead",
    "half alive",
    "bewildered",
    "dizzy",
    "stupified",
    "discombobulated",
    "entangled",
    "trammelled",
    "ensnared in #possessivePronouns2 thoughts",
    "implicated in my own #noun",
    "vexxed",
    "poisoned",
    "pooped",
    "enmeshed in #noun",
    "bogged down by #noun",
    "embroiled in #noun",
    "enmeshed in #noun",
    "ensnared in #noun",
    "entangled in #noun",
    "floundered",
    "implicated",
    "involved",
    "stuck in #noun",
    "tangled",
    "trapped in #noun",
    "clung",
    "decelerated",
    "detained",
    "dirty",
    "entrapped in #noun",
    "sunk",
    "snared in #noun",
    "soiled",
    "set back by #noun",
    "slowed down by #noun",
    "slowed by a #noun",

  ];

  static var modalVerbs = [
    "can",
    "could",
    "may",
    "might",
    "must",
    "ought to",
    "shall",
    "should",
    "will",
    "would",
  ];
}