class WaysToStartAThought
{
  static var waysToStartAThought =
  [
    "Above all",
    "Again",
    "Also",
    "And yet",
    "As a result",
    "As a rule",
    "As an illustration",
    "Initially",
    "As usual",
    "As well as",
    "Assuredly",
    "Because",
    "Besides",
    "Certainly",
    "Chiefly",
    "Comparatively",
    "Consequently",
    "Conversely",
    "Correspondingly",
    "Coupled with",
    "Due to",
    "Especially",
    "Especially",
    "Firstly,",
    "For example",
    "For instance",
    "For one thing",
    "For the most part",
    "For this purpose",
    "For this reason",
    "Furthermore",
    "Furthermore,",
    "Generally speaking",
    "Granted",
    "Hence",
    "Lately",
    "However",
    "However,",
    "I reckon",
    "Ideally,",
    "Identically",
    "In addition",
    "In comparison",
    "In contrast",
    "In fact",
    "In particular",
    "In this case",
    "In this situation",
    "Including",
    "Indeed",
    "Instead",
    "It boils down to this:",
    "Likewise",
    "Markedly",
    "Moreover",
    "Moreover,",
    "Namely",
    "Nevertheless",
    "Next,",
    "No doubt",
    "Obviously",
    "Of course",
    "On the contrary",
    "On the one hand",
    "On the other hand",
    "Optimally",
    "Ordinarily",
    "Other than",
    "Otherwise",
    "Outside of",
    "Particularly",
    "Presumably, this means",
    "Rather",
    "Most recently",
    "Remember,",
    "Similarly",
    "Since",
    "Singularly",
    "So then",
    "Specifically",
    "Still",
    "Subsequently",
    "Such as",
    "Surely,",
    "The result is",
    "Therefore",
    "Thereupon",
    "This can be seen in",
    "This is why",
    "Thus",
    "Undoubtedly",
    "Unquestionably",
    "Usually",
    "Whereas",
    "Wherefore",
    "Yet,",
  ];

  static var greatOpenings =
  [
    "Throughout the ages",
    "Since the dawn of time",
    "By chance",
    "In the beginning",
    "For generations",
    "Behold",
    "For you are #stateOfExistence",
    "As for now",
    "Time after time",
    "For you",
    "For a long time",
    "It has always been said",
    "Born and raised by #groupsOfAnimalsOrPeople",
    "Born and raised in the #landsAndEmpires",

  ];
}