class WaysToStartAThought
{
  static var waysToStartAThought =
  [
    "Above all",
    "Again",
    "Also",
    "And yet",
    "As a result",
    "As a rule",
    "As an illustration",
    "As usual",
    "As well as",
    "Assuredly",
    "Because",
    "Besides",
    "Certainly",
    "Chiefly",
    "Comparatively",
    "Consequently",
    "Conversely",
    "Correspondingly",
    "Coupled with",
    "Due to",
    "Especially",
    "Especially",
    "Firstly,",
    "For example",
    "For instance",
    "For one thing",
    "For the most part",
    "For this purpose",
    "For this reason",
    "Furthermore",
    "Furthermore,",
    "Generally speaking",
    "Granted",
    "Hence",
    "However",
    "However,",
    "I reckon",
    "Ideally,",
    "Identically",
    "In addition",
    "In comparison",
    "In contrast",
    "In fact",
    "In particular",
    "In this case",
    "In this situation",
    "Including",
    "Indeed",
    "Instead",
    "It boils down to this:",
    "Likewise",
    "Markedly",
    "Moreover",
    "Moreover,",
    "Namely",
    "Nevertheless",
    "Next,",
    "No doubt",
    "Obviously",
    "Of course",
    "On the contrary",
    "On the one hand",
    "On the other hand",
    "Optimally",
    "Ordinarily",
    "Other than",
    "Otherwise",
    "Outside of",
    "Particularly",
    "Presumably, this means",
    "Rather",
    "Remember,",
    "Similarly",
    "Since",
    "Singularly",
    "So then",
    "Specifically",
    "Still",
    "Subsequently",
    "Such as",
    "Surely,",
    "The result is",
    "Therefore",
    "Thereupon",
    "This can be seen in",
    "This is why",
    "Thus",
    "Undoubtedly",
    "Unquestionably",
    "Usually",
    "Whereas",
    "Wherefore",
    "Yet,",

  ];
}