class Names
{
  static var names =
  [
  "Moon",
  "Earth",
  "Mercury",
  "Venus",
  "Mars",
  "Ceres",
  "Jupiter",
  "Saturn",
  "Uranus",
  "Neptune",
  "Pluto",
  "Helios",
  "Hermes",
  "Cytherea",
  "Gaia",
  "Luna",
  "Selene",
  "Ares",
  "Kelvin",
  "Saint Germain",
  "Demeter",
  "Zeus",
  "Jupiter",
  "Cronos",
  "Saturn",
  "Uranus",
  "Poseidon",
  "Hades",
  "Vallis Alpes",
  "Vallis Baade",
  "Vallis Bohr",
  "Vallis Bouvard",
  "Vallis Capella",
  "Vallis Inghirami",
  "Vallis Palitzsch",
  "Vallis Planck",
  "Vallis Rheita",
  "Vallis Schrödinger",
  "Vallis Schröteri",
  "Vallis Snellius",
  "Sea of Vapors",
  "Southern Sea",
  "Serpent Sea",
  "Sea of Crisis",
  "Eastern Sea",
  "Sea of Cleverness",
  "Mare Anguis",
  "Mare Australe",
  "Mare Cognitum",
  "Mare Crisium",
  "Mare Fecunditatis",
  "Mare Frigoris",
  "Mare Humboldtianum",
  "Mare Humorum",
  "Mare Imbrium",
  "Mare Ingenii",
  "Mare Insularum",
  "Mare Marginis",
  "Mare Moscoviense",
  "Mare Nectaris",
  "Mare Nubium",
  "Mare Orientale",
  "Mare Serenitatis",
  "Mare Smythii",
  "Mare Spumans",
  "Mare Tranquillitatis",
  "Mare Undarum",
  "Lake of Sorrow",
  "Lake of Death",
  "Lake of Dreams",
  "Lake of Time",
  "Mare Vaporum",
  "Oceanus Procellarum",
  "Lacus Aestatis",
  "Lacus Autumni",
  "Lacus Bonitatis",
  "Lacus Doloris",
  "Lacus Excellentiae",
  "Lacus Felicitatis",
  "Lacus Gaudii",
  "Lacus Hiemalis",
  "Lacus Lenitatis",
  "Lacus Luxuriae",
  "Lacus Mortis",
  "Lacus Oblivionis",
  "Lacus Odii",
  "Lacus Perseverantiae",
  "Lacus Solitudinis",
  "Lacus Somniorum",
  "Lacus Spei",
  "Lacus Temporis",
  "Lacus Timoris",
  "Lacus Veris",
  "Lunar Sinus",
  "Paludes",
  "Palus Epidemiarum",
  "Palus Putredinis",
  "Palus Somni",
  "Sinus Aestuum",
  "Sinus Amoris",
  "Sinus Asperitatis",
  "Sinus Concordiae",
  "Sinus Fidei",
  "Sinus Honoris",
  "Sinus Iridum",
  "Sinus Lunicus",
  "Sinus Medii",
  "Sinus Roris",
  "Sinus Successus",
  "Pleides",
  "Mons Agnes",
  "Mons Ampère",
  "Mons André",
  "Mons Ardeshir",
  "Mons Argaeus",
  "Mont Blanc",
  "Mons Bradley",
  "Mons Delisle",
  "Mons Dieter",
  "Mons Dilip",
  "Mons Esam",
  "Mons Ganau",
  "Mons Gruithuisen Delta",
  "Mons Gruithuisen Gamma",
  "Mons Hadley",
  "Mons Hadley Delta",
  "Mons Hansteen",
  "Mons Herodotus",
  "Mons Huygens",
  "Mons La Hire",
  "Mons Maraldi",
  "Mons Moro",
  "Mons Penck",
  "Mons Pico",
  "Mons Piton",
  "Mons Rümker",
  "Mons Usov",
  "Mons Vinogradov[5]",
  "Mons Vitruvius",
  "Mons Wolff",
  "Montes Agricola",
  "Montes Alpes",
  "Montes Apenninus",
  "Montes Archimedes",
  "Montes Carpatus",
  "Montes Caucasus",
  "Montes Cordillera",
  "Montes Haemus",
  "Montes Harbinger",
  "Montes Jura",
  "Montes Pyrenaeus",
  "Montes Recti",
  "Montes Riphaeus",
  "Montes Rook",
  "Montes Secchi",
  "Montes Spitzbergen",
  "Montes Taurus",
  "Montes Teneriffe",
  "Catena Abulfeda",
  "Catena Artamonov",
  "Catena Brigitte",
  "Catena Davy",
  "Catena Dziewulski",
  "Catena Gregory",
  "Catena Humboldt",
  "Catena Krafft",
  "Catena Kurchatov",
  "Catena Leuschner",
  "Catena Littrow",
  "Catena Lucretius",
  "Catena Mendeleev",
  "Catena Michelson",
  "Catena Pierre",
  "Catena Sumner",
  "Catena Sylvester",
  "Catena Taruntius",
  "Catena Timocharis",
  "Catena Yuri",
  "Dorsa Aldrovandi",
  "Dorsa Andrusov",
  "Dorsa Argand",
  "Dorsa Barlow",
  "Dorsa Burnet",
  "Dorsa Cato",
  "Dorsa Dana",
  "Dorsa Ewing",
  "Dorsa Geikie",
  "Dorsa Harker",
  "Dorsa Lister",
  "Dorsa Mawson",
  "Dorsa Rubey",
  "Dorsa Smirnov",
  "Dorsa Sorby",
  "Dorsa Stille",
  "Dorsa Tetyaev",
  "Dorsa Whiston",
  "Dorsum Arduino",
  "Dorsum Azara",
  "Dorsum Bucher",
  "Dorsum Buckland",
  "Dorsum Cayeux",
  "Dorsum Cloos",
  "Dorsum Cushman",
  "Dorsum Gast",
  "Dorsum Grabau",
  "Dorsum Guettard",
  "Dorsum Heim",
  "Dorsum Higazy",
  "Dorsum Nicol",
  "Dorsum Oppel",
  "Dorsum Owen",
  "Dorsum Scilla",
  "Dorsum Termier",
  "Dorsum Thera",
  "Dorsum Von Cotta",
  "Dorsum Zirkel",
  "Promontorium Agarum",
  "Promontorium Agassiz",
  "Promontorium Archerusia",
  "Promontorium Deville",
  "Promontorium Fresnel",
  "Promontorium Heraclides",
  "Promontorium Kelvin",
  "Promontorium Laplace",
  "Promontorium Taenarium",
  "Rima Agatharchides",
  "Rima Agricola",
  "Rima Archytas",
  "Rima Ariadaeus",
  "Rima Billy",
  "Rima Birt",
  "Rima Bradley",
  "Rima Brayley",
  "Rima Calippus",
  "Rima Cardanus",
  "Rima Carmen",
  "Rima Cauchy",
  "Rima Cleomedes",
  "Rima Cleopatra",
  "Rima Conon",
  "Rima Dawes",
  "Rima Delisle",
  "Rima Diophantus",
  "Rima Draper",
  "Rima Euler",
  "Rima Flammarion",
  "Rima Furnerius",
  "Rima G. Bond",
  "Rima Galilaei",
  "Rima Gärtner",
  "Rima Gay-Lussac",
  "Rima Hadley",
  "Rima Hansteen",
  "Rima Hesiodus",
  "Rima Hyginus",
  "Rima Jansen",
  "Rima Krieger",
  "Rima Mairan",
  "Rima Marcello",
  "Rima Marius",
  "Rima Messier",
  "Rima Milichius",
  "Rima Oppolzer",
  "Rima Réaumur",
  "Rima Reiko",
  "Rima Rudolf",
  "Rima Schröter",
  "Rima Sharp",
  "Rima Sheepshanks",
  "Rima Siegfried",
  "Rima Suess",
  "Rima Sung-Mei",
  "Rima T. Mayer",
  "Rima Vladimir",
  "Rima Wan-Yu",
  "Rima Yangel",
  "Rima Zahia",
  "Rimae Alphonsus",
  "Rimae Apollonius",
  "Rimae Archimedes",
  "Rimae Aristarchus",
  "Rimae Arzachel",
  "Rimae Atlas",
  "Rimae Bode",
  "Rimae Boscovich",
  "Rimae Chacornac",
  "Rimae Daniell",
  "Rimae Darwin",
  "Rimae Doppelmayer",
  "Rimae Focas",
  "Rimae Fresnel",
  "Rimae de Gasparis",
  "Rimae Gassendi",
  "Rimae Gerard",
  "Rimae Goclenius",
  "Rimae Grimaldi",
  "Rimae Hypatia",
  "Rimae Janssen",
  "Rimae Kopff",
  "Rimae Liebig",
  "Rimae Littrow",
  "Rimae Maclear",
  "Rimae Maestlin",
  "Rimae Maupertuis",
  "Rimae Menelaus",
  "Rimae Mersenius",
  "Rimae Opelt",
  "Rimae Palmieri",
  "Rimae Parry",
  "Rimae Petavius",
  "Rimae Pettit",
  "Rimae Pitatus",
  "Rimae Plato",
  "Rimae Plinius",
  "Rimae Posidonius",
  "Rimae Prinz",
  "Rimae Ramsden",
  "Rimae Repsold",
  "Rimae Riccioli",
  "Rimae Ritter",
  "Rimae Römer",
  "Rimae Secchi",
  "Rimae Sirsalis",
  "Rimae Sosigenes",
  "Rimae Sulpicius Gallus",
  "Rimae Taruntius",
  "Rimae Theaetetus",
  "Rimae Triesnecker",
  "Rimae Vasco da Gama",
  "Rimae Zupus",
  "Rupes Altai",
  "Rupes Boris",
  "Rupes Cauchy",
  "Rupes Kelvin",
  "Rupes Liebig",
  "Rupes Mercator",
  "Rupes Recta",
  "Rupes Toscanelli",
  "Insula Ventorum",
  "Island of Winds",
  "Peninsula Fulminu",
  "Terra Caloris",
  "Terra Fertilitatis",
  "Terrae Grandinis",
  "Terrae Manna",
  "Terra Niuiu (Terra Nivium)",
  "Terra Pruinæ",
  "Terra Sanitatis",
  "Terra Siccitatis",
  "Terra Sterilitatis",
  "Terra Vigoris",
  "Terra Vitæ",
  "Land of Sterility",
  "Land of Frost",
  "Peninsula of Thunder",
  "Abbe",
  "Abbot",
  "Abel",
  "Abenezra",
  "Abetti",
  "Abul Wáfa",
  "Abulfeda",
  "Acosta",
  "Adams",
  "Aepinus",
  "Agatharchides",
  "Agrippa",
  "Airy",
  "Aitken",
  "Akis",
  "Alan",
  "Al-Bakri",
  "Albategnius",
  "Albert",
  "Al-Biruni",
  "Alden",
  "Alder",
  "Aldrin",
  "Alekhin",
  "Alexander",
  "Alfraganus",
  "Alhazen",
  "Aliacensis",
  "Al-Khwarizmi",
  "Almanon",
  "Al-Marrakushi",
  "Aloha",
  "Alpetragius",
  "Alphonsus",
  "Alter",
  "Ameghino",
  "Amici",
  "Ammonius",
  "Amontons",
  "Amundsen",
  "Anaxagoras",
  "Anaximander",
  "Anaximenes",
  "Anděl",
  "Anders",
  "Anderson",
  "Andersson",
  "Andronov",
  "Ango",
  "Angström",
  "Ann",
  "Annegrit",
  "Ansgarius",
  "Antoniadi",
  "Anuchin",
  "Anville",
  "Apianus",
  "Apollo",
  "Apollonius",
  "Appleton",
  "Arago",
  "Aratus",
  "Archimedes",
  "Archytas",
  "Argelander",
  "Ariadaeus",
  "Aristarchus",
  "Aristillus",
  "Aristoteles",
  "Armiński",
  "Armstrong",
  "Arnold",
  "Arrhenius",
  "Artamonov",
  "Artem’ev",
  "Artemis",
  "Artsimovich",
  "Aryabhata",
  "Arzachel",
  "Asada",
  "Asclepi",
  "Ashbrook",
  "Aston",
  "Atlas",
  "Atwood",
  "Autolycus",
  "Auwers",
  "Auzout",
  "Avery",
  "Avicenna",
  "Avogadro",
  "Azophi",
  "Baade",
  "Babakin",
  "Babbage",
  "Babcock",
  "Back",
  "Backlund",
  "Baco",
  "Baillaud",
  "Bailly",
  "Baily",
  "Balandin",
  "Balboa",
  "Baldet",
  "Ball",
  "Balmer",
  "Banachiewicz",
  "Bancroft",
  "Banting",
  "Barbier",
  "Barkla",
  "Barnard",
  "Barocius",
  "Barringer",
  "Barrow",
  "Bartels",
  "Bawa",
  "Bayer",
  "Beals",
  "Beaumont",
  "Becquerel",
  "Bečvář",
  "Beer",
  "Behaim",
  "Beijerinck",
  "Beketov",
  "Béla",
  "Bel’kovich",
  "Bell",
  "Bellinsgauzen",
  "Bellot",
  "Belopol’skiy",
  "Belyaev",
  "Benedict",
  "Bergman",
  "Bergstrand",
  "Berkner",
  "Berlage",
  "Bernoulli",
  "Berosus",
  "Berzelius",
  "Bessarion",
  "Bessel",
  "Bettinus",
  "Bhabha",
  "Bianchini",
  "Biela",
  "Bilharz",
  "Billy",
  "Bingham",
  "Biot",
  "Birkeland",
  "Birkhoff",
  "Birmingham",
  "Birt",
  "Bi Sheng",
  "Bjerknes",
  "Black",
  "Blackett",
  "Blagg",
  "Blancanus",
  "Blanchard",
  "Blanchinus",
  "Blazhko",
  "Bliss",
  "Bobillier",
  "Bobone",
  "Bode",
  "Boethius",
  "Boguslawsky",
  "Bohnenberger",
  "Bohr",
  "Bok",
  "Boltzmann",
  "Bolyai",
  "Bombelli",
  "Bondarenko",
  "Bonpland",
  "Boole",
  "Borda",
  "Borel",
  "Boris",
  "Borman",
  "Born",
  "Borya",
  "Bosch",
  "Boscovich",
  "Bose",
  "Boss",
  "Bouguer",
  "Boussingault",
  "Bowditch",
  "Bowen",
  "Boyle",
  "Brackett",
  "Bragg",
  "Brashear",
  "Braude",
  "Brayley",
  "Bredikhin",
  "Breislak",
  "Brenner",
  "Brewster",
  "Brianchon",
  "Bridgman",
  "Briggs",
  "Brisbane",
  "Bronk",
  "Brouwer",
  "Brown",
  "Bruce",
  "Brunner",
  "Buch",
  "Buffon",
  "Buisson",
  "Bullialdus",
  "Bunsen",
  "Burckhardt",
  "Bürg",
  "Burnham",
  "Büsching",
  "Butlerov",
  "Buys-Ballot",
  "Byrd",
  "Byrgius",
  "Cabannes",
  "Cabeus",
  "Cailleux",
  "Cai Lun",
  "Cajal",
  "Cajori",
  "Calippus",
  "Cameron",
  "Campanus",
  "Campbell",
  "Cannizzaro",
  "Cannon",
  "Cantor",
  "Capella",
  "Capuanus",
  "Cardanus",
  "Carlini",
  "Carlos",
  "Carmichael",
  "Carnot",
  "Carol",
  "Carpenter",
  "Carrel",
  "Carrillo",
  "Carrington",
  "Cartan",
  "Carver",
  "Casatus",
  "Cassegrain",
  "Cassini",
  "Catalán",
  "Catharina",
  "Cauchy",
  "Cavalerius",
  "Cavendish",
  "Caventou",
  "Cayley",
  "Celsius",
  "Censorinus",
  "Cepheus",
  "Chacornac",
  "Chadwick",
  "Chaffee",
  "Challis",
  "Chalonge",
  "Chamberlin",
  "Champollion",
  "Chandler",
  "Chang Heng",
  "Chang-Ngo",
  "Chant",
  "Chaplygin",
  "Chapman",
  "Chappe",
  "Chappell",
  "Charles",
  "Charlier",
  "Chaucer",
  "Chauvenet",
  "Chawla",
  "Chebyshev",
  "Chernyshev",
  "Chevallier",
  "Ching-Te",
  "Chladni",
  "Chrétien",
  "Cichus",
  "Clairaut",
  "Clausius",
  "Clavius",
  "Cleomedes",
  "Cleostratus",
  "Clerke",
  "Coblentz",
  "Cockcroft",
  "Collins",
  "Colombo",
  "Compton",
  "Comrie",
  "Comstock",
  "Condon",
  "Condorcet",
  "Congreve",
  "Conon",
  "Copernicus",
  "Cori",
  "Coriolis",
  "Couder",
  "Coulomb",
  "Courtney",
  "Cremona",
  "Crile",
  "Crocco",
  "Crommelin",
  "Crookes",
  "Crozier",
  "Crüger",
  "Ctesibius",
  "Curie",
  "Curtius",
  "Cusanus",
  "Cuvier",
  "Cyrano",
  "Cyrillus",
  "Cysatus",
  "da Vinci",
  "Daedalus",
  "Dag",
  "Daguerre",
  "Dale",
  "d’Alembert",
  "Dalton",
  "Daly",
  "Damoiseau",
  "Daniell",
  "Danjon",
  "Dante",
  "Darney",
  "D’Arrest",
  "D’Arsonval",
  "Darwin",
  "Das",
  "Daubrée",
  "Davisson",
  "Davy",
  "Dawes",
  "De Forest",
  "de Gasparis",
  "de Gerlache",
  "De La Rue",
  "De Moraes",
  "De Morgan",
  "De Roy",
  "De Sitter",
  "De Vico",
  "De Vries",
  "Debes",
  "Debus",
  "Debye",
  "Dechen",
  "Delambre",
  "Delaunay",
  "Delia",
  "Delisle",
  "Dellinger",
  "Delmotte",
  "Delporte",
  "Deluc",
  "Dembowski",
  "Democritus",
  "Demonax",
  "Denning",
  "Desargues",
  "Descartes",
  "Deseilligny",
  "Deslandres",
  "Deutsch",
  "Dewar",
  "Diana",
  "Diderot",
  "Dionysius",
  "Diophantus",
  "Dirichlet",
  "Dobrovol’skiy",
  "Doerfel",
  "Dollond",
  "Donati",
  "Donna",
  "Donner",
  "Doppelmayer",
  "Doppler",
  "Douglass",
  "Dove",
  "Draper",
  "Drebbel",
  "Dreyer",
  "Drude",
  "Dryden",
  "Drygalski",
  "Dubyago",
  "Dufay",
  "Dugan",
  "Dunér",
  "Dunthorne",
  "Dyson",
  "Dziewulski",
  "Eckert",
  "Eddington",
  "Edison",
  "Egede",
  "Ehrlich",
  "Eichstadt",
  "Eijkman",
  "Eimmart",
  "Einstein",
  "Einthoven",
  "Elger",
  "Ellerman",
  "Ellison",
  "Elmer",
  "Elvey",
  "Emden",
  "Encke",
  "Endymion",
  "Engel’gardt",
  "Eötvös",
  "Epigenes",
  "Epimenides",
  "Eratosthenes",
  "Erlanger",
  "Erro",
  "Esclangon",
  "Esnault-Pelterie",
  "Espin",
  "Euclides",
  "Euctemon",
  "Eudoxus",
  "Euler",
  "Evans",
  "Evdokimov",
  "Evershed",
  "Ewen",
  "Fabbroni",
  "Fabricius",
  "Fabry",
  "Fahrenheit",
  "Fairouz",
  "Faraday",
  "Faustini",
  "Fauth",
  "Faye",
  "Fechner",
  "Fedorov",
  "Felix",
  "Fényi",
  "Feoktistov",
  "Fermat",
  "Fermi",
  "Fernelius",
  "Fersman",
  "Fesenkov",
  "Feuillée",
  "Fibiger",
  "Finsch",
  "Finsen",
  "Firmicus",
  "Firsov",
  "Fischer",
  "Fitzgerald",
  "Fizeau",
  "Flammarion",
  "Flamsteed",
  "Fleming",
  "Florensky",
  "Florey",
  "Focas",
  "Fontana",
  "Fontenelle",
  "Foster",
  "Foucault",
  "Fourier",
  "Fowler",
  "Fox",
  "Fra Mauro",
  "Fracastorius",
  "Franck",
  "Franz",
  "Fraunhofer",
  "Fredholm",
  "Freud",
  "Freundlich",
  "Fridman",
  "Froelich",
  "Fryxell",
  "Furnerius",
  ];
}