class StatesOfExistence
{
  //trying using two states together
  static String getTwoStates()
  {
    return states[1] + " " + states[0];
  }

  //past tense
  static var states = [
    "destitute",
    "displaced",
    "dispossessed",
    "derelict",
    "down-and-out",
    "itinerant",
    "outcast",
    "refugee",
    "vagabond",
    "vagrant",
    "wandering",
    "abandoned",
    "banished",
    "deported",
    "desolate",
    "disinherited",
    "estranged",
    "exiled",
    "asleep",
    "forlorn",
    "forsaken",
    "friendless",
    "houseless",
    "uncared-for",
    "unhoused",
    "unsettled",
    "unwelcome",
    "without a roof",
    "abandoned",
    "prostrate",
    "homeless",
    "bankrupt",
    "enraged",
    "laid to waste",
    "loaded",
    "becoming",
    "restored",
    "euphoric",
    "rotational",
    "immovable",
    "abstract",
    "fluid",
    "eternal",
    "lower state",
    "protypical",
    "archetypal"
    "preface",
    "sad",
    "mosaic",
    "rough",
    "deteriorating",
    "comforting",
    "forged",
    "misunderstood",
    "aesthetic",
    "intoxicated",
    "natural",
    "performative",
    "static",
    "blown",
    "bought",
    "broken",
    "built",
    "burned",
    "Calm",
    "caught",
    "chosen",
    "complete",
    "discharged",
    "dived",
    "done",
    "drowned",
    "drunken",
    "eaten",
    "empty",
    "fallen",
    "faltered",
    "existing",
    "fatigued",
    "forgiven",
    "forgotten",
    "frozen",
    "gone",
    "grown",
//    "heard",
    "decrepitude",
    "held",
    "hidden",
    "hung",
    "hurt",
    "impoverished",
    "invisible",
    "kept",
    "diminished importance",
    "lamentation",
    "glory gone",
    "forlorn in an inevitable decrepitude",
    "known",
    "laid",
    "left for dead",
    "lent",
    "lost",
    "lost to time",
    "overflowed",
    "overworked",
    "paid",
    "real",
    "authentic",
    "read",
    "decrypted",
    "encrypted",
    "hopelessly mangled",
    "ridden",
    "risen",
    "sent",
    "shown",
    "shut",
    "shut",
//    "slept",
    "sold",
    "spent",
    "spilled",
    "spoken",
    "stolen",
    "sung",
    "taken",
    "thrown",
    "told",
    "torn",
    "visible",
    "weary",
    "well over",
    "wrecked",
    "written",
  ];

}